clone_folder: C:\projects\compmech

clone_depth: 1
build: false

environment:
  global:
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\continuous-integration\\appveyor\\cmd_in_env.cmd"

  matrix:
      - PYTHON_VERSION: 2.7
        PYTHON_ARCH: 32
        MINICONDA: C:\Miniconda

      - PYTHON_VERSION: 2.7
        PYTHON_ARCH: 64
        MINICONDA: C:\Miniconda-x64

      - PYTHON_VERSION: 3.4
        PYTHON_ARCH: 32
        MINICONDA: C:\Miniconda3

      - PYTHON_VERSION: 3.4
        PYTHON_ARCH: 64
        MINICONDA: C:\Miniconda3-x64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - echo Environment Variables:
  - set
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n testenv python=%PYTHON_VERSION% numpy scipy pytest cython libpython
  - activate testenv
  # fixing bug with environment
  - cd ..
  - cd ..
  - set DEFAULT_ENV=%CD%
  - dir
  - cd MinGW
  - dir
  - dir lib
  - cd mingw32
  - dir
  - dir lib
  - set PATH=C:\MinGW\lib;C:\MinGW\mingw32\lib;C:\MinGW\mingw32\bin;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  - set
  - "CALL %CMD_IN_ENV% python setup.py install"
  # removing local libraries to be sure the installation was correct
  - del /s *.dll
  - del /s *.so
  - del /s *.h

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - set
  - cd compmech\integrate
  - py.test --cache-clear
  - cd ..\panel\tests
  #TODO some tests will not run in AppVeyor
  - py.test --cache-clear test_panel_aero.py
  - py.test --cache-clear test_panel_freq.py
  - py.test --cache-clear test_panel_lb.py
  - cd ..\assembly\tests
  - py.test --cache-clear
  - cd ..\..\..\stiffpanelbay
  - py.test --cache-clear
