clone_folder: C:\projects\compmech

clone_depth: 1
build: false

environment:
  global:
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\continuous-integration\\appveyor\\cmd_in_env.cmd"

  matrix:
      - PYTHON_VERSION: 2.7
        PYTHON_ARCH: 32
        MINICONDA: C:\Miniconda
        VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\vcvarsall.bat x86"

      - PYTHON_VERSION: 2.7
        PYTHON_ARCH: 64
        MINICONDA: C:\Miniconda-x64
        VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\vcvarsall.bat x86"

      - PYTHON_VERSION: 3.4
        PYTHON_ARCH: 32
        MINICONDA: C:\Miniconda3
        VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\vcvarsall.bat x86"

      - PYTHON_VERSION: 3.4
        PYTHON_ARCH: 64
        MINICONDA: C:\Miniconda3-x64
        VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\vcvarsall.bat x64"

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - echo Environment Variables:
  - set
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n testenv python=%PYTHON_VERSION% numpy scipy pytest cython libpython
  - activate testenv
  - %VCVARS%
  - set DISTUTILS_USE_SDK=1
  - python setup.py install
  #- "CALL %CMD_IN_ENV% python setup.py install"
  # removing local libraries to be sure the installation was correct
  - del /s *.dll
  - del /s *.so
  - del /s *.h

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - set
  - py.test --cache-clear
